### ISSUE TITLE
lattice CLI on Windows?

### ISSUE THREAD

**Issue by hantsy** [spring-guides/gs-spring-cloud-and-lattice#2]
How to use Lattice CLI on Windows system?

**Comment by gregturn** [comment]
So far, Lattice only seems to have instructions for Mac and Linux (https://github.com/cloudfoundry-incubator/lattice/tree/master/ltc).

You may wish to open an issue at https://github.com/cloudfoundry-incubator/lattice.

**Comment by jbayer** [comment]
have you tried building the windows version of ltc with a windows machine with go installed and configured? the commands are listed in the 'install from source' part and probably just need a slight modification for windows vs linux nuances: https://github.com/cloudfoundry-incubator/lattice/tree/v0.2.3/ltc#installing-from-source
